export type SecretaryState = "BOOTING" | "SLEEP" | "WAKING" | "LISTENING" | "TRANSCRIBING" | "THINKING" | "APPROVAL" | "SPEAKING" | "ERROR" | "OFFLINE";

export type SecretaryEvent =
  | "CONNECTED" | "CONNECT_FAILED" | "DISCONNECTED" | "CLAP_DETECTED" | "WAKE_FINISHED"
  | "AUDIO_FINAL" | "AGENT_STARTED" | "APPROVAL_REQUIRED" | "AGENT_COMPLETED"
  | "IDLE" | "FINISH" | "SYSTEM_ERROR" | "RETRY" | "CONTINUE";
